# Generated by Django 3.1.5 on 2021-02-15 17:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
